/* automatically generated by rust-bindgen 0.72.1 */

pub type __s8 = crate::ctypes::c_schar;
pub type __u8 = crate::ctypes::c_uchar;
pub type __s16 = crate::ctypes::c_short;
pub type __u16 = crate::ctypes::c_ushort;
pub type __s32 = crate::ctypes::c_int;
pub type __u32 = crate::ctypes::c_uint;
pub type __s64 = crate::ctypes::c_longlong;
pub type __u64 = crate::ctypes::c_ulonglong;
pub type __kernel_key_t = crate::ctypes::c_int;
pub type __kernel_mqd_t = crate::ctypes::c_int;
pub type __kernel_mode_t = crate::ctypes::c_ushort;
pub type __kernel_ipc_pid_t = crate::ctypes::c_ushort;
pub type __kernel_uid_t = crate::ctypes::c_ushort;
pub type __kernel_gid_t = crate::ctypes::c_ushort;
pub type __kernel_old_dev_t = crate::ctypes::c_ushort;
pub type __kernel_long_t = crate::ctypes::c_long;
pub type __kernel_ulong_t = crate::ctypes::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_pid_t = crate::ctypes::c_int;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = crate::ctypes::c_int;
pub type __kernel_uid32_t = crate::ctypes::c_uint;
pub type __kernel_gid32_t = crate::ctypes::c_uint;
pub type __kernel_old_uid_t = __kernel_uid_t;
pub type __kernel_old_gid_t = __kernel_gid_t;
pub type __kernel_size_t = crate::ctypes::c_uint;
pub type __kernel_ssize_t = crate::ctypes::c_int;
pub type __kernel_ptrdiff_t = crate::ctypes::c_int;
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = crate::ctypes::c_longlong;
pub type __kernel_old_time_t = __kernel_long_t;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = crate::ctypes::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = crate::ctypes::c_int;
pub type __kernel_clockid_t = crate::ctypes::c_int;
pub type __kernel_caddr_t = *mut crate::ctypes::c_char;
pub type __kernel_uid16_t = crate::ctypes::c_ushort;
pub type __kernel_gid16_t = crate::ctypes::c_ushort;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = crate::ctypes::c_uint;
pub type snd_pcm_uframes_t = crate::ctypes::c_ulong;
pub type snd_pcm_sframes_t = crate::ctypes::c_long;
pub type snd_pcm_access_t = crate::ctypes::c_int;
pub type snd_pcm_format_t = crate::ctypes::c_int;
pub type snd_pcm_subformat_t = crate::ctypes::c_int;
pub type snd_pcm_state_t = crate::ctypes::c_int;
pub type snd_pcm_hw_param_t = crate::ctypes::c_int;
pub type __pad_before_uframe = [crate::ctypes::c_char; 0usize];
pub type __pad_after_uframe = [crate::ctypes::c_char; 4usize];
pub type snd_ctl_elem_type_t = crate::ctypes::c_int;
pub type snd_ctl_elem_iface_t = crate::ctypes::c_int;
#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
storage: Storage,
}
#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
#[repr(C)]
pub struct __BindgenUnionField<T>(::core::marker::PhantomData<T>);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
pub tv_sec: crate::ctypes::c_long,
pub tv_nsec: crate::ctypes::c_long,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_aes_iec958 {
pub status: [crate::ctypes::c_uchar; 24usize],
pub subcode: [crate::ctypes::c_uchar; 147usize],
pub pad: crate::ctypes::c_uchar,
pub dig_subframe: [crate::ctypes::c_uchar; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_cea_861_aud_if {
pub db1_ct_cc: crate::ctypes::c_uchar,
pub db2_sf_ss: crate::ctypes::c_uchar,
pub db3: crate::ctypes::c_uchar,
pub db4_ca: crate::ctypes::c_uchar,
pub db5_dminh_lsv: crate::ctypes::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_hwdep_info {
pub device: crate::ctypes::c_uint,
pub card: crate::ctypes::c_int,
pub id: [crate::ctypes::c_uchar; 64usize],
pub name: [crate::ctypes::c_uchar; 80usize],
pub iface: crate::ctypes::c_int,
pub reserved: [crate::ctypes::c_uchar; 64usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_hwdep_dsp_status {
pub version: crate::ctypes::c_uint,
pub id: [crate::ctypes::c_uchar; 32usize],
pub num_dsps: crate::ctypes::c_uint,
pub dsp_loaded: crate::ctypes::c_uint,
pub chip_ready: crate::ctypes::c_uint,
pub reserved: [crate::ctypes::c_uchar; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_hwdep_dsp_image {
pub index: crate::ctypes::c_uint,
pub name: [crate::ctypes::c_uchar; 64usize],
pub image: *mut crate::ctypes::c_uchar,
pub length: usize,
pub driver_data: crate::ctypes::c_ulong,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_pcm_info {
pub device: crate::ctypes::c_uint,
pub subdevice: crate::ctypes::c_uint,
pub stream: crate::ctypes::c_int,
pub card: crate::ctypes::c_int,
pub id: [crate::ctypes::c_uchar; 64usize],
pub name: [crate::ctypes::c_uchar; 80usize],
pub subname: [crate::ctypes::c_uchar; 32usize],
pub dev_class: crate::ctypes::c_int,
pub dev_subclass: crate::ctypes::c_int,
pub subdevices_count: crate::ctypes::c_uint,
pub subdevices_avail: crate::ctypes::c_uint,
pub pad1: [crate::ctypes::c_uchar; 16usize],
pub reserved: [crate::ctypes::c_uchar; 64usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_interval {
pub min: crate::ctypes::c_uint,
pub max: crate::ctypes::c_uint,
pub _bitfield_align_1: [u8; 0],
pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
pub __bindgen_padding_0: [u8; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_mask {
pub bits: [__u32; 8usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_pcm_hw_params {
pub flags: crate::ctypes::c_uint,
pub masks: [snd_mask; 3usize],
pub mres: [snd_mask; 5usize],
pub intervals: [snd_interval; 12usize],
pub ires: [snd_interval; 9usize],
pub rmask: crate::ctypes::c_uint,
pub cmask: crate::ctypes::c_uint,
pub info: crate::ctypes::c_uint,
pub msbits: crate::ctypes::c_uint,
pub rate_num: crate::ctypes::c_uint,
pub rate_den: crate::ctypes::c_uint,
pub fifo_size: snd_pcm_uframes_t,
pub sync: [crate::ctypes::c_uchar; 16usize],
pub reserved: [crate::ctypes::c_uchar; 48usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_pcm_sw_params {
pub tstamp_mode: crate::ctypes::c_int,
pub period_step: crate::ctypes::c_uint,
pub sleep_min: crate::ctypes::c_uint,
pub avail_min: snd_pcm_uframes_t,
pub xfer_align: snd_pcm_uframes_t,
pub start_threshold: snd_pcm_uframes_t,
pub stop_threshold: snd_pcm_uframes_t,
pub silence_threshold: snd_pcm_uframes_t,
pub silence_size: snd_pcm_uframes_t,
pub boundary: snd_pcm_uframes_t,
pub proto: crate::ctypes::c_uint,
pub tstamp_type: crate::ctypes::c_uint,
pub reserved: [crate::ctypes::c_uchar; 56usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_pcm_channel_info {
pub channel: crate::ctypes::c_uint,
pub offset: __kernel_off_t,
pub first: crate::ctypes::c_uint,
pub step: crate::ctypes::c_uint,
}
#[repr(C)]
#[derive(Debug)]
pub struct __time_pad {
pub pad: __IncompleteArrayField<crate::ctypes::c_uchar>,
}
#[repr(C)]
#[derive(Debug)]
pub struct snd_pcm_status {
pub state: snd_pcm_state_t,
pub pad1: __time_pad,
pub trigger_tstamp: timespec,
pub tstamp: timespec,
pub appl_ptr: snd_pcm_uframes_t,
pub hw_ptr: snd_pcm_uframes_t,
pub delay: snd_pcm_sframes_t,
pub avail: snd_pcm_uframes_t,
pub avail_max: snd_pcm_uframes_t,
pub overrange: snd_pcm_uframes_t,
pub suspended_state: snd_pcm_state_t,
pub audio_tstamp_data: __u32,
pub audio_tstamp: timespec,
pub driver_tstamp: timespec,
pub audio_tstamp_accuracy: __u32,
pub reserved: [crate::ctypes::c_uchar; 36usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __snd_timespec64 {
pub tv_sec: __s64,
pub tv_nsec: __s64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_pcm_mmap_status {
pub state: snd_pcm_state_t,
pub pad1: crate::ctypes::c_int,
pub hw_ptr: snd_pcm_uframes_t,
pub tstamp: timespec,
pub suspended_state: snd_pcm_state_t,
pub audio_tstamp: timespec,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_pcm_mmap_control {
pub appl_ptr: snd_pcm_uframes_t,
pub avail_min: snd_pcm_uframes_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct snd_pcm_sync_ptr {
pub flags: crate::ctypes::c_uint,
pub s: snd_pcm_sync_ptr__bindgen_ty_1,
pub c: snd_pcm_sync_ptr__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug)]
pub struct __snd_pcm_mmap_status64 {
pub state: snd_pcm_state_t,
pub pad1: __u32,
pub __pad1: __pad_before_uframe,
pub hw_ptr: snd_pcm_uframes_t,
pub __pad2: __pad_after_uframe,
pub tstamp: __snd_timespec64,
pub suspended_state: snd_pcm_state_t,
pub pad3: __u32,
pub audio_tstamp: __snd_timespec64,
}
#[repr(C)]
#[derive(Debug)]
pub struct __snd_pcm_mmap_control64 {
pub __pad1: __pad_before_uframe,
pub appl_ptr: snd_pcm_uframes_t,
pub __pad2: __pad_before_uframe,
pub __pad3: __pad_before_uframe,
pub avail_min: snd_pcm_uframes_t,
pub __pad4: __pad_after_uframe,
}
#[repr(C)]
pub struct __snd_pcm_sync_ptr64 {
pub flags: __u32,
pub pad1: __u32,
pub s: __snd_pcm_sync_ptr64__bindgen_ty_1,
pub c: __snd_pcm_sync_ptr64__bindgen_ty_2,
}
#[repr(C)]
pub struct __snd_pcm_sync_ptr64__bindgen_ty_1 {
pub status: __BindgenUnionField<__snd_pcm_mmap_status64>,
pub reserved: __BindgenUnionField<[crate::ctypes::c_uchar; 64usize]>,
pub bindgen_union_field: [u32; 16usize],
}
#[repr(C)]
pub struct __snd_pcm_sync_ptr64__bindgen_ty_2 {
pub control: __BindgenUnionField<__snd_pcm_mmap_control64>,
pub reserved: __BindgenUnionField<[crate::ctypes::c_uchar; 64usize]>,
pub bindgen_union_field: [u32; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_xferi {
pub result: snd_pcm_sframes_t,
pub buf: *mut crate::ctypes::c_void,
pub frames: snd_pcm_uframes_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_xfern {
pub result: snd_pcm_sframes_t,
pub bufs: *mut *mut crate::ctypes::c_void,
pub frames: snd_pcm_uframes_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_rawmidi_info {
pub device: crate::ctypes::c_uint,
pub subdevice: crate::ctypes::c_uint,
pub stream: crate::ctypes::c_int,
pub card: crate::ctypes::c_int,
pub flags: crate::ctypes::c_uint,
pub id: [crate::ctypes::c_uchar; 64usize],
pub name: [crate::ctypes::c_uchar; 80usize],
pub subname: [crate::ctypes::c_uchar; 32usize],
pub subdevices_count: crate::ctypes::c_uint,
pub subdevices_avail: crate::ctypes::c_uint,
pub tied_device: crate::ctypes::c_int,
pub reserved: [crate::ctypes::c_uchar; 60usize],
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct snd_rawmidi_framing_tstamp {
pub frame_type: __u8,
pub length: __u8,
pub reserved: [__u8; 2usize],
pub tv_nsec: __u32,
pub tv_sec: __u64,
pub data: [__u8; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_rawmidi_params {
pub stream: crate::ctypes::c_int,
pub buffer_size: usize,
pub avail_min: usize,
pub _bitfield_align_1: [u8; 0],
pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
pub mode: crate::ctypes::c_uint,
pub reserved: [crate::ctypes::c_uchar; 12usize],
}
#[repr(C)]
#[derive(Debug)]
pub struct snd_rawmidi_status {
pub stream: crate::ctypes::c_int,
pub pad1: __time_pad,
pub tstamp: timespec,
pub avail: usize,
pub xruns: usize,
pub reserved: [crate::ctypes::c_uchar; 16usize],
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct snd_ump_endpoint_info {
pub card: crate::ctypes::c_int,
pub device: crate::ctypes::c_int,
pub flags: crate::ctypes::c_uint,
pub protocol_caps: crate::ctypes::c_uint,
pub protocol: crate::ctypes::c_uint,
pub num_blocks: crate::ctypes::c_uint,
pub version: crate::ctypes::c_ushort,
pub family_id: crate::ctypes::c_ushort,
pub model_id: crate::ctypes::c_ushort,
pub manufacturer_id: crate::ctypes::c_uint,
pub sw_revision: [crate::ctypes::c_uchar; 4usize],
pub padding: crate::ctypes::c_ushort,
pub name: [crate::ctypes::c_uchar; 128usize],
pub product_id: [crate::ctypes::c_uchar; 128usize],
pub reserved: [crate::ctypes::c_uchar; 32usize],
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct snd_ump_block_info {
pub card: crate::ctypes::c_int,
pub device: crate::ctypes::c_int,
pub block_id: crate::ctypes::c_uchar,
pub direction: crate::ctypes::c_uchar,
pub active: crate::ctypes::c_uchar,
pub first_group: crate::ctypes::c_uchar,
pub num_groups: crate::ctypes::c_uchar,
pub midi_ci_version: crate::ctypes::c_uchar,
pub sysex8_streams: crate::ctypes::c_uchar,
pub ui_hint: crate::ctypes::c_uchar,
pub flags: crate::ctypes::c_uint,
pub name: [crate::ctypes::c_uchar; 128usize],
pub reserved: [crate::ctypes::c_uchar; 32usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_id {
pub dev_class: crate::ctypes::c_int,
pub dev_sclass: crate::ctypes::c_int,
pub card: crate::ctypes::c_int,
pub device: crate::ctypes::c_int,
pub subdevice: crate::ctypes::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_ginfo {
pub tid: snd_timer_id,
pub flags: crate::ctypes::c_uint,
pub card: crate::ctypes::c_int,
pub id: [crate::ctypes::c_uchar; 64usize],
pub name: [crate::ctypes::c_uchar; 80usize],
pub reserved0: crate::ctypes::c_ulong,
pub resolution: crate::ctypes::c_ulong,
pub resolution_min: crate::ctypes::c_ulong,
pub resolution_max: crate::ctypes::c_ulong,
pub clients: crate::ctypes::c_uint,
pub reserved: [crate::ctypes::c_uchar; 32usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_gparams {
pub tid: snd_timer_id,
pub period_num: crate::ctypes::c_ulong,
pub period_den: crate::ctypes::c_ulong,
pub reserved: [crate::ctypes::c_uchar; 32usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_gstatus {
pub tid: snd_timer_id,
pub resolution: crate::ctypes::c_ulong,
pub resolution_num: crate::ctypes::c_ulong,
pub resolution_den: crate::ctypes::c_ulong,
pub reserved: [crate::ctypes::c_uchar; 32usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_select {
pub id: snd_timer_id,
pub reserved: [crate::ctypes::c_uchar; 32usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_info {
pub flags: crate::ctypes::c_uint,
pub card: crate::ctypes::c_int,
pub id: [crate::ctypes::c_uchar; 64usize],
pub name: [crate::ctypes::c_uchar; 80usize],
pub reserved0: crate::ctypes::c_ulong,
pub resolution: crate::ctypes::c_ulong,
pub reserved: [crate::ctypes::c_uchar; 64usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_params {
pub flags: crate::ctypes::c_uint,
pub ticks: crate::ctypes::c_uint,
pub queue_size: crate::ctypes::c_uint,
pub reserved0: crate::ctypes::c_uint,
pub filter: crate::ctypes::c_uint,
pub reserved: [crate::ctypes::c_uchar; 60usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_status {
pub tstamp: timespec,
pub resolution: crate::ctypes::c_uint,
pub lost: crate::ctypes::c_uint,
pub overrun: crate::ctypes::c_uint,
pub queue: crate::ctypes::c_uint,
pub reserved: [crate::ctypes::c_uchar; 64usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_uinfo {
pub resolution: __u64,
pub fd: crate::ctypes::c_int,
pub id: crate::ctypes::c_uint,
pub reserved: [crate::ctypes::c_uchar; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_timer_read {
pub resolution: crate::ctypes::c_uint,
pub ticks: crate::ctypes::c_uint,
}
#[repr(C)]
#[derive(Debug)]
pub struct snd_timer_tread {
pub event: crate::ctypes::c_int,
pub pad1: __time_pad,
pub tstamp: timespec,
pub val: crate::ctypes::c_uint,
pub pad2: __time_pad,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_ctl_card_info {
pub card: crate::ctypes::c_int,
pub pad: crate::ctypes::c_int,
pub id: [crate::ctypes::c_uchar; 16usize],
pub driver: [crate::ctypes::c_uchar; 16usize],
pub name: [crate::ctypes::c_uchar; 32usize],
pub longname: [crate::ctypes::c_uchar; 80usize],
pub reserved_: [crate::ctypes::c_uchar; 16usize],
pub mixername: [crate::ctypes::c_uchar; 80usize],
pub components: [crate::ctypes::c_uchar; 128usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_ctl_elem_id {
pub numid: crate::ctypes::c_uint,
pub iface: snd_ctl_elem_iface_t,
pub device: crate::ctypes::c_uint,
pub subdevice: crate::ctypes::c_uint,
pub name: [crate::ctypes::c_uchar; 44usize],
pub index: crate::ctypes::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_ctl_elem_list {
pub offset: crate::ctypes::c_uint,
pub space: crate::ctypes::c_uint,
pub used: crate::ctypes::c_uint,
pub count: crate::ctypes::c_uint,
pub pids: *mut snd_ctl_elem_id,
pub reserved: [crate::ctypes::c_uchar; 50usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct snd_ctl_elem_info {
pub id: snd_ctl_elem_id,
pub type_: snd_ctl_elem_type_t,
pub access: crate::ctypes::c_uint,
pub count: crate::ctypes::c_uint,
pub owner: __kernel_pid_t,
pub value: snd_ctl_elem_info__bindgen_ty_1,
pub reserved: [crate::ctypes::c_uchar; 64usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_ctl_elem_info__bindgen_ty_1__bindgen_ty_1 {
pub min: crate::ctypes::c_long,
pub max: crate::ctypes::c_long,
pub step: crate::ctypes::c_long,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_ctl_elem_info__bindgen_ty_1__bindgen_ty_2 {
pub min: crate::ctypes::c_longlong,
pub max: crate::ctypes::c_longlong,
pub step: crate::ctypes::c_longlong,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_ctl_elem_info__bindgen_ty_1__bindgen_ty_3 {
pub items: crate::ctypes::c_uint,
pub item: crate::ctypes::c_uint,
pub name: [crate::ctypes::c_char; 64usize],
pub names_ptr: __u64,
pub names_length: crate::ctypes::c_uint,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct snd_ctl_elem_value {
pub id: snd_ctl_elem_id,
pub _bitfield_align_1: [u8; 0],
pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
pub value: snd_ctl_elem_value__bindgen_ty_1,
pub reserved: [crate::ctypes::c_uchar; 128usize],
}
#[repr(C)]
#[derive(Debug)]
pub struct snd_ctl_tlv {
pub numid: crate::ctypes::c_uint,
pub length: crate::ctypes::c_uint,
pub tlv: __IncompleteArrayField<crate::ctypes::c_uint>,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct snd_ctl_event {
pub type_: crate::ctypes::c_int,
pub data: snd_ctl_event__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct snd_ctl_event__bindgen_ty_1__bindgen_ty_1 {
pub mask: crate::ctypes::c_uint,
pub id: snd_ctl_elem_id,
}
pub const __BITS_PER_LONG_LONG: u32 = 64;
pub const __LITTLE_ENDIAN: u32 = 1234;
pub const AES_IEC958_STATUS_SIZE: u32 = 24;
pub const SNDRV_PCM_INFO_MMAP: u32 = 1;
pub const SNDRV_PCM_INFO_MMAP_VALID: u32 = 2;
pub const SNDRV_PCM_INFO_DOUBLE: u32 = 4;
pub const SNDRV_PCM_INFO_BATCH: u32 = 16;
pub const SNDRV_PCM_INFO_SYNC_APPLPTR: u32 = 32;
pub const SNDRV_PCM_INFO_PERFECT_DRAIN: u32 = 64;
pub const SNDRV_PCM_INFO_INTERLEAVED: u32 = 256;
pub const SNDRV_PCM_INFO_NONINTERLEAVED: u32 = 512;
pub const SNDRV_PCM_INFO_COMPLEX: u32 = 1024;
pub const SNDRV_PCM_INFO_BLOCK_TRANSFER: u32 = 65536;
pub const SNDRV_PCM_INFO_OVERRANGE: u32 = 131072;
pub const SNDRV_PCM_INFO_RESUME: u32 = 262144;
pub const SNDRV_PCM_INFO_PAUSE: u32 = 524288;
pub const SNDRV_PCM_INFO_HALF_DUPLEX: u32 = 1048576;
pub const SNDRV_PCM_INFO_JOINT_DUPLEX: u32 = 2097152;
pub const SNDRV_PCM_INFO_SYNC_START: u32 = 4194304;
pub const SNDRV_PCM_INFO_NO_PERIOD_WAKEUP: u32 = 8388608;
pub const SNDRV_PCM_INFO_HAS_WALL_CLOCK: u32 = 16777216;
pub const SNDRV_PCM_INFO_HAS_LINK_ATIME: u32 = 16777216;
pub const SNDRV_PCM_INFO_HAS_LINK_ABSOLUTE_ATIME: u32 = 33554432;
pub const SNDRV_PCM_INFO_HAS_LINK_ESTIMATED_ATIME: u32 = 67108864;
pub const SNDRV_PCM_INFO_HAS_LINK_SYNCHRONIZED_ATIME: u32 = 134217728;
pub const SNDRV_PCM_INFO_EXPLICIT_SYNC: u32 = 268435456;
pub const SNDRV_PCM_INFO_NO_REWINDS: u32 = 536870912;
pub const SNDRV_PCM_INFO_DRAIN_TRIGGER: u32 = 1073741824;
pub const SNDRV_PCM_INFO_FIFO_IN_FRAMES: u32 = 2147483648;
pub const SNDRV_PCM_HW_PARAM_ACCESS: u32 = 0;
pub const SNDRV_PCM_HW_PARAM_FORMAT: u32 = 1;
pub const SNDRV_PCM_HW_PARAM_SUBFORMAT: u32 = 2;
pub const SNDRV_PCM_HW_PARAM_FIRST_MASK: u32 = 0;
pub const SNDRV_PCM_HW_PARAM_LAST_MASK: u32 = 2;
pub const SNDRV_PCM_HW_PARAM_SAMPLE_BITS: u32 = 8;
pub const SNDRV_PCM_HW_PARAM_FRAME_BITS: u32 = 9;
pub const SNDRV_PCM_HW_PARAM_CHANNELS: u32 = 10;
pub const SNDRV_PCM_HW_PARAM_RATE: u32 = 11;
pub const SNDRV_PCM_HW_PARAM_PERIOD_TIME: u32 = 12;
pub const SNDRV_PCM_HW_PARAM_PERIOD_SIZE: u32 = 13;
pub const SNDRV_PCM_HW_PARAM_PERIOD_BYTES: u32 = 14;
pub const SNDRV_PCM_HW_PARAM_PERIODS: u32 = 15;
pub const SNDRV_PCM_HW_PARAM_BUFFER_TIME: u32 = 16;
pub const SNDRV_PCM_HW_PARAM_BUFFER_SIZE: u32 = 17;
pub const SNDRV_PCM_HW_PARAM_BUFFER_BYTES: u32 = 18;
pub const SNDRV_PCM_HW_PARAM_TICK_TIME: u32 = 19;
pub const SNDRV_PCM_HW_PARAM_FIRST_INTERVAL: u32 = 8;
pub const SNDRV_PCM_HW_PARAM_LAST_INTERVAL: u32 = 19;
pub const SNDRV_PCM_HW_PARAMS_NORESAMPLE: u32 = 1;
pub const SNDRV_PCM_HW_PARAMS_EXPORT_BUFFER: u32 = 2;
pub const SNDRV_PCM_HW_PARAMS_NO_PERIOD_WAKEUP: u32 = 4;
pub const SNDRV_PCM_HW_PARAMS_NO_DRAIN_SILENCE: u32 = 8;
pub const SNDRV_MASK_MAX: u32 = 256;
pub const SNDRV_PCM_SYNC_PTR_HWSYNC: u32 = 1;
pub const SNDRV_PCM_SYNC_PTR_APPL: u32 = 2;
pub const SNDRV_PCM_SYNC_PTR_AVAIL_MIN: u32 = 4;
pub const SNDRV_CHMAP_POSITION_MASK: u32 = 65535;
pub const SNDRV_CHMAP_PHASE_INVERSE: u32 = 65536;
pub const SNDRV_CHMAP_DRIVER_SPEC: u32 = 131072;
pub const SNDRV_RAWMIDI_INFO_OUTPUT: u32 = 1;
pub const SNDRV_RAWMIDI_INFO_INPUT: u32 = 2;
pub const SNDRV_RAWMIDI_INFO_DUPLEX: u32 = 4;
pub const SNDRV_RAWMIDI_INFO_UMP: u32 = 8;
pub const SNDRV_RAWMIDI_INFO_STREAM_INACTIVE: u32 = 16;
pub const SNDRV_RAWMIDI_DEVICE_UNKNOWN: u32 = 0;
pub const SNDRV_RAWMIDI_MODE_FRAMING_MASK: u32 = 7;
pub const SNDRV_RAWMIDI_MODE_FRAMING_SHIFT: u32 = 0;
pub const SNDRV_RAWMIDI_MODE_FRAMING_NONE: u32 = 0;
pub const SNDRV_RAWMIDI_MODE_FRAMING_TSTAMP: u32 = 1;
pub const SNDRV_RAWMIDI_MODE_CLOCK_MASK: u32 = 56;
pub const SNDRV_RAWMIDI_MODE_CLOCK_SHIFT: u32 = 3;
pub const SNDRV_RAWMIDI_MODE_CLOCK_NONE: u32 = 0;
pub const SNDRV_RAWMIDI_MODE_CLOCK_REALTIME: u32 = 8;
pub const SNDRV_RAWMIDI_MODE_CLOCK_MONOTONIC: u32 = 16;
pub const SNDRV_RAWMIDI_MODE_CLOCK_MONOTONIC_RAW: u32 = 24;
pub const SNDRV_RAWMIDI_FRAMING_DATA_LENGTH: u32 = 16;
pub const SNDRV_UMP_EP_INFO_STATIC_BLOCKS: u32 = 1;
pub const SNDRV_UMP_EP_INFO_PROTO_MIDI_MASK: u32 = 768;
pub const SNDRV_UMP_EP_INFO_PROTO_MIDI1: u32 = 256;
pub const SNDRV_UMP_EP_INFO_PROTO_MIDI2: u32 = 512;
pub const SNDRV_UMP_EP_INFO_PROTO_JRTS_MASK: u32 = 3;
pub const SNDRV_UMP_EP_INFO_PROTO_JRTS_TX: u32 = 1;
pub const SNDRV_UMP_EP_INFO_PROTO_JRTS_RX: u32 = 2;
pub const SNDRV_UMP_DIR_INPUT: u32 = 1;
pub const SNDRV_UMP_DIR_OUTPUT: u32 = 2;
pub const SNDRV_UMP_DIR_BIDIRECTION: u32 = 3;
pub const SNDRV_UMP_BLOCK_IS_MIDI1: u32 = 1;
pub const SNDRV_UMP_BLOCK_IS_LOWSPEED: u32 = 2;
pub const SNDRV_UMP_BLOCK_UI_HINT_UNKNOWN: u32 = 0;
pub const SNDRV_UMP_BLOCK_UI_HINT_RECEIVER: u32 = 1;
pub const SNDRV_UMP_BLOCK_UI_HINT_SENDER: u32 = 2;
pub const SNDRV_UMP_BLOCK_UI_HINT_BOTH: u32 = 3;
pub const SNDRV_UMP_MAX_GROUPS: u32 = 16;
pub const SNDRV_UMP_MAX_BLOCKS: u32 = 32;
pub const SNDRV_TIMER_GLOBAL_SYSTEM: u32 = 0;
pub const SNDRV_TIMER_GLOBAL_RTC: u32 = 1;
pub const SNDRV_TIMER_GLOBAL_HPET: u32 = 2;
pub const SNDRV_TIMER_GLOBAL_HRTIMER: u32 = 3;
pub const SNDRV_TIMER_GLOBAL_UDRIVEN: u32 = 4;
pub const SNDRV_TIMER_FLG_SLAVE: u32 = 1;
pub const SNDRV_TIMER_PSFLG_AUTO: u32 = 1;
pub const SNDRV_TIMER_PSFLG_EXCLUSIVE: u32 = 2;
pub const SNDRV_TIMER_PSFLG_EARLY_EVENT: u32 = 4;
pub const SNDRV_CTL_ELEM_ACCESS_READ: u32 = 1;
pub const SNDRV_CTL_ELEM_ACCESS_WRITE: u32 = 2;
pub const SNDRV_CTL_ELEM_ACCESS_READWRITE: u32 = 3;
pub const SNDRV_CTL_ELEM_ACCESS_VOLATILE: u32 = 4;
pub const SNDRV_CTL_ELEM_ACCESS_TLV_READ: u32 = 16;
pub const SNDRV_CTL_ELEM_ACCESS_TLV_WRITE: u32 = 32;
pub const SNDRV_CTL_ELEM_ACCESS_TLV_READWRITE: u32 = 48;
pub const SNDRV_CTL_ELEM_ACCESS_TLV_COMMAND: u32 = 64;
pub const SNDRV_CTL_ELEM_ACCESS_INACTIVE: u32 = 256;
pub const SNDRV_CTL_ELEM_ACCESS_LOCK: u32 = 512;
pub const SNDRV_CTL_ELEM_ACCESS_OWNER: u32 = 1024;
pub const SNDRV_CTL_ELEM_ACCESS_TLV_CALLBACK: u32 = 268435456;
pub const SNDRV_CTL_ELEM_ACCESS_USER: u32 = 536870912;
pub const SNDRV_CTL_POWER_D0: u32 = 0;
pub const SNDRV_CTL_POWER_D1: u32 = 256;
pub const SNDRV_CTL_POWER_D2: u32 = 512;
pub const SNDRV_CTL_POWER_D3: u32 = 768;
pub const SNDRV_CTL_POWER_D3hot: u32 = 768;
pub const SNDRV_CTL_POWER_D3cold: u32 = 769;
pub const SNDRV_CTL_ELEM_ID_NAME_MAXLEN: u32 = 44;
pub const SNDRV_CTL_EVENT_MASK_VALUE: u32 = 1;
pub const SNDRV_CTL_EVENT_MASK_INFO: u32 = 2;
pub const SNDRV_CTL_EVENT_MASK_ADD: u32 = 4;
pub const SNDRV_CTL_EVENT_MASK_TLV: u32 = 8;
pub const SNDRV_CTL_EVENT_MASK_REMOVE: i32 = -1;
pub const SNDRV_CTL_NAME_NONE: &[u8; 1] = b"\0";
pub const SNDRV_CTL_NAME_PLAYBACK: &[u8; 10] = b"Playback \0";
pub const SNDRV_CTL_NAME_CAPTURE: &[u8; 9] = b"Capture \0";
pub const SNDRV_CTL_NAME_IEC958_NONE: &[u8; 1] = b"\0";
pub const SNDRV_CTL_NAME_IEC958_SWITCH: &[u8; 7] = b"Switch\0";
pub const SNDRV_CTL_NAME_IEC958_VOLUME: &[u8; 7] = b"Volume\0";
pub const SNDRV_CTL_NAME_IEC958_DEFAULT: &[u8; 8] = b"Default\0";
pub const SNDRV_CTL_NAME_IEC958_MASK: &[u8; 5] = b"Mask\0";
pub const SNDRV_CTL_NAME_IEC958_CON_MASK: &[u8; 9] = b"Con Mask\0";
pub const SNDRV_CTL_NAME_IEC958_PRO_MASK: &[u8; 9] = b"Pro Mask\0";
pub const SNDRV_CTL_NAME_IEC958_PCM_STREAM: &[u8; 11] = b"PCM Stream\0";
pub const SNDRV_HWDEP_IFACE_OPL2: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_OPL2;
pub const SNDRV_HWDEP_IFACE_OPL3: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_OPL3;
pub const SNDRV_HWDEP_IFACE_OPL4: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_OPL4;
pub const SNDRV_HWDEP_IFACE_SB16CSP: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_SB16CSP;
pub const SNDRV_HWDEP_IFACE_EMU10K1: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_EMU10K1;
pub const SNDRV_HWDEP_IFACE_YSS225: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_YSS225;
pub const SNDRV_HWDEP_IFACE_ICS2115: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_ICS2115;
pub const SNDRV_HWDEP_IFACE_SSCAPE: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_SSCAPE;
pub const SNDRV_HWDEP_IFACE_VX: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_VX;
pub const SNDRV_HWDEP_IFACE_MIXART: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_MIXART;
pub const SNDRV_HWDEP_IFACE_USX2Y: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_USX2Y;
pub const SNDRV_HWDEP_IFACE_EMUX_WAVETABLE: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_EMUX_WAVETABLE;
pub const SNDRV_HWDEP_IFACE_BLUETOOTH: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_BLUETOOTH;
pub const SNDRV_HWDEP_IFACE_USX2Y_PCM: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_USX2Y_PCM;
pub const SNDRV_HWDEP_IFACE_PCXHR: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_PCXHR;
pub const SNDRV_HWDEP_IFACE_SB_RC: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_SB_RC;
pub const SNDRV_HWDEP_IFACE_HDA: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_HDA;
pub const SNDRV_HWDEP_IFACE_USB_STREAM: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_USB_STREAM;
pub const SNDRV_HWDEP_IFACE_FW_DICE: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_FW_DICE;
pub const SNDRV_HWDEP_IFACE_FW_FIREWORKS: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_FW_FIREWORKS;
pub const SNDRV_HWDEP_IFACE_FW_BEBOB: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_FW_BEBOB;
pub const SNDRV_HWDEP_IFACE_FW_OXFW: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_FW_OXFW;
pub const SNDRV_HWDEP_IFACE_FW_DIGI00X: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_FW_DIGI00X;
pub const SNDRV_HWDEP_IFACE_FW_TASCAM: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_FW_TASCAM;
pub const SNDRV_HWDEP_IFACE_LINE6: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_LINE6;
pub const SNDRV_HWDEP_IFACE_FW_MOTU: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_FW_MOTU;
pub const SNDRV_HWDEP_IFACE_FW_FIREFACE: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_FW_FIREFACE;
pub const SNDRV_HWDEP_IFACE_LAST: _bindgen_ty_1 = _bindgen_ty_1::SNDRV_HWDEP_IFACE_FW_FIREFACE;
pub const SNDRV_PCM_CLASS_GENERIC: _bindgen_ty_2 = _bindgen_ty_2::SNDRV_PCM_CLASS_GENERIC;
pub const SNDRV_PCM_CLASS_MULTI: _bindgen_ty_2 = _bindgen_ty_2::SNDRV_PCM_CLASS_MULTI;
pub const SNDRV_PCM_CLASS_MODEM: _bindgen_ty_2 = _bindgen_ty_2::SNDRV_PCM_CLASS_MODEM;
pub const SNDRV_PCM_CLASS_DIGITIZER: _bindgen_ty_2 = _bindgen_ty_2::SNDRV_PCM_CLASS_DIGITIZER;
pub const SNDRV_PCM_CLASS_LAST: _bindgen_ty_2 = _bindgen_ty_2::SNDRV_PCM_CLASS_DIGITIZER;
pub const SNDRV_PCM_SUBCLASS_GENERIC_MIX: _bindgen_ty_3 = _bindgen_ty_3::SNDRV_PCM_SUBCLASS_GENERIC_MIX;
pub const SNDRV_PCM_SUBCLASS_MULTI_MIX: _bindgen_ty_3 = _bindgen_ty_3::SNDRV_PCM_SUBCLASS_MULTI_MIX;
pub const SNDRV_PCM_SUBCLASS_LAST: _bindgen_ty_3 = _bindgen_ty_3::SNDRV_PCM_SUBCLASS_MULTI_MIX;
pub const SNDRV_PCM_STREAM_PLAYBACK: _bindgen_ty_4 = _bindgen_ty_4::SNDRV_PCM_STREAM_PLAYBACK;
pub const SNDRV_PCM_STREAM_CAPTURE: _bindgen_ty_4 = _bindgen_ty_4::SNDRV_PCM_STREAM_CAPTURE;
pub const SNDRV_PCM_STREAM_LAST: _bindgen_ty_4 = _bindgen_ty_4::SNDRV_PCM_STREAM_CAPTURE;
pub const SNDRV_PCM_MMAP_OFFSET_DATA: _bindgen_ty_5 = _bindgen_ty_5::SNDRV_PCM_MMAP_OFFSET_DATA;
pub const SNDRV_PCM_MMAP_OFFSET_STATUS_OLD: _bindgen_ty_5 = _bindgen_ty_5::SNDRV_PCM_MMAP_OFFSET_STATUS_OLD;
pub const SNDRV_PCM_MMAP_OFFSET_CONTROL_OLD: _bindgen_ty_5 = _bindgen_ty_5::SNDRV_PCM_MMAP_OFFSET_CONTROL_OLD;
pub const SNDRV_PCM_MMAP_OFFSET_STATUS_NEW: _bindgen_ty_5 = _bindgen_ty_5::SNDRV_PCM_MMAP_OFFSET_STATUS_NEW;
pub const SNDRV_PCM_MMAP_OFFSET_CONTROL_NEW: _bindgen_ty_5 = _bindgen_ty_5::SNDRV_PCM_MMAP_OFFSET_CONTROL_NEW;
pub const SNDRV_PCM_MMAP_OFFSET_STATUS: _bindgen_ty_5 = _bindgen_ty_5::SNDRV_PCM_MMAP_OFFSET_STATUS_OLD;
pub const SNDRV_PCM_MMAP_OFFSET_CONTROL: _bindgen_ty_5 = _bindgen_ty_5::SNDRV_PCM_MMAP_OFFSET_CONTROL_OLD;
pub const SNDRV_PCM_TSTAMP_NONE: _bindgen_ty_6 = _bindgen_ty_6::SNDRV_PCM_TSTAMP_NONE;
pub const SNDRV_PCM_TSTAMP_ENABLE: _bindgen_ty_6 = _bindgen_ty_6::SNDRV_PCM_TSTAMP_ENABLE;
pub const SNDRV_PCM_TSTAMP_LAST: _bindgen_ty_6 = _bindgen_ty_6::SNDRV_PCM_TSTAMP_ENABLE;
pub const SNDRV_PCM_AUDIO_TSTAMP_TYPE_COMPAT: _bindgen_ty_7 = _bindgen_ty_7::SNDRV_PCM_AUDIO_TSTAMP_TYPE_COMPAT;
pub const SNDRV_PCM_AUDIO_TSTAMP_TYPE_DEFAULT: _bindgen_ty_7 = _bindgen_ty_7::SNDRV_PCM_AUDIO_TSTAMP_TYPE_DEFAULT;
pub const SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK: _bindgen_ty_7 = _bindgen_ty_7::SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK;
pub const SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_ABSOLUTE: _bindgen_ty_7 = _bindgen_ty_7::SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_ABSOLUTE;
pub const SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_ESTIMATED: _bindgen_ty_7 = _bindgen_ty_7::SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_ESTIMATED;
pub const SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_SYNCHRONIZED: _bindgen_ty_7 = _bindgen_ty_7::SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_SYNCHRONIZED;
pub const SNDRV_PCM_AUDIO_TSTAMP_TYPE_LAST: _bindgen_ty_7 = _bindgen_ty_7::SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_SYNCHRONIZED;
pub const SNDRV_PCM_TSTAMP_TYPE_GETTIMEOFDAY: _bindgen_ty_8 = _bindgen_ty_8::SNDRV_PCM_TSTAMP_TYPE_GETTIMEOFDAY;
pub const SNDRV_PCM_TSTAMP_TYPE_MONOTONIC: _bindgen_ty_8 = _bindgen_ty_8::SNDRV_PCM_TSTAMP_TYPE_MONOTONIC;
pub const SNDRV_PCM_TSTAMP_TYPE_MONOTONIC_RAW: _bindgen_ty_8 = _bindgen_ty_8::SNDRV_PCM_TSTAMP_TYPE_MONOTONIC_RAW;
pub const SNDRV_PCM_TSTAMP_TYPE_LAST: _bindgen_ty_8 = _bindgen_ty_8::SNDRV_PCM_TSTAMP_TYPE_MONOTONIC_RAW;
pub const SNDRV_CHMAP_UNKNOWN: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_UNKNOWN;
pub const SNDRV_CHMAP_NA: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_NA;
pub const SNDRV_CHMAP_MONO: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_MONO;
pub const SNDRV_CHMAP_FL: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FL;
pub const SNDRV_CHMAP_FR: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FR;
pub const SNDRV_CHMAP_RL: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_RL;
pub const SNDRV_CHMAP_RR: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_RR;
pub const SNDRV_CHMAP_FC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FC;
pub const SNDRV_CHMAP_LFE: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_LFE;
pub const SNDRV_CHMAP_SL: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_SL;
pub const SNDRV_CHMAP_SR: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_SR;
pub const SNDRV_CHMAP_RC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_RC;
pub const SNDRV_CHMAP_FLC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FLC;
pub const SNDRV_CHMAP_FRC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FRC;
pub const SNDRV_CHMAP_RLC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_RLC;
pub const SNDRV_CHMAP_RRC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_RRC;
pub const SNDRV_CHMAP_FLW: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FLW;
pub const SNDRV_CHMAP_FRW: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FRW;
pub const SNDRV_CHMAP_FLH: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FLH;
pub const SNDRV_CHMAP_FCH: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FCH;
pub const SNDRV_CHMAP_FRH: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_FRH;
pub const SNDRV_CHMAP_TC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TC;
pub const SNDRV_CHMAP_TFL: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TFL;
pub const SNDRV_CHMAP_TFR: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TFR;
pub const SNDRV_CHMAP_TFC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TFC;
pub const SNDRV_CHMAP_TRL: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TRL;
pub const SNDRV_CHMAP_TRR: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TRR;
pub const SNDRV_CHMAP_TRC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TRC;
pub const SNDRV_CHMAP_TFLC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TFLC;
pub const SNDRV_CHMAP_TFRC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TFRC;
pub const SNDRV_CHMAP_TSL: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TSL;
pub const SNDRV_CHMAP_TSR: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_TSR;
pub const SNDRV_CHMAP_LLFE: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_LLFE;
pub const SNDRV_CHMAP_RLFE: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_RLFE;
pub const SNDRV_CHMAP_BC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_BC;
pub const SNDRV_CHMAP_BLC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_BLC;
pub const SNDRV_CHMAP_BRC: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_BRC;
pub const SNDRV_CHMAP_LAST: _bindgen_ty_9 = _bindgen_ty_9::SNDRV_CHMAP_BRC;
pub const SNDRV_RAWMIDI_STREAM_OUTPUT: _bindgen_ty_10 = _bindgen_ty_10::SNDRV_RAWMIDI_STREAM_OUTPUT;
pub const SNDRV_RAWMIDI_STREAM_INPUT: _bindgen_ty_10 = _bindgen_ty_10::SNDRV_RAWMIDI_STREAM_INPUT;
pub const SNDRV_RAWMIDI_STREAM_LAST: _bindgen_ty_10 = _bindgen_ty_10::SNDRV_RAWMIDI_STREAM_INPUT;
pub const SNDRV_TIMER_CLASS_NONE: _bindgen_ty_11 = _bindgen_ty_11::SNDRV_TIMER_CLASS_NONE;
pub const SNDRV_TIMER_CLASS_SLAVE: _bindgen_ty_11 = _bindgen_ty_11::SNDRV_TIMER_CLASS_SLAVE;
pub const SNDRV_TIMER_CLASS_GLOBAL: _bindgen_ty_11 = _bindgen_ty_11::SNDRV_TIMER_CLASS_GLOBAL;
pub const SNDRV_TIMER_CLASS_CARD: _bindgen_ty_11 = _bindgen_ty_11::SNDRV_TIMER_CLASS_CARD;
pub const SNDRV_TIMER_CLASS_PCM: _bindgen_ty_11 = _bindgen_ty_11::SNDRV_TIMER_CLASS_PCM;
pub const SNDRV_TIMER_CLASS_LAST: _bindgen_ty_11 = _bindgen_ty_11::SNDRV_TIMER_CLASS_PCM;
pub const SNDRV_TIMER_SCLASS_NONE: _bindgen_ty_12 = _bindgen_ty_12::SNDRV_TIMER_SCLASS_NONE;
pub const SNDRV_TIMER_SCLASS_APPLICATION: _bindgen_ty_12 = _bindgen_ty_12::SNDRV_TIMER_SCLASS_APPLICATION;
pub const SNDRV_TIMER_SCLASS_SEQUENCER: _bindgen_ty_12 = _bindgen_ty_12::SNDRV_TIMER_SCLASS_SEQUENCER;
pub const SNDRV_TIMER_SCLASS_OSS_SEQUENCER: _bindgen_ty_12 = _bindgen_ty_12::SNDRV_TIMER_SCLASS_OSS_SEQUENCER;
pub const SNDRV_TIMER_SCLASS_LAST: _bindgen_ty_12 = _bindgen_ty_12::SNDRV_TIMER_SCLASS_OSS_SEQUENCER;
pub const SNDRV_TIMER_EVENT_RESOLUTION: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_RESOLUTION;
pub const SNDRV_TIMER_EVENT_TICK: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_TICK;
pub const SNDRV_TIMER_EVENT_START: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_START;
pub const SNDRV_TIMER_EVENT_STOP: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_STOP;
pub const SNDRV_TIMER_EVENT_CONTINUE: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_CONTINUE;
pub const SNDRV_TIMER_EVENT_PAUSE: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_PAUSE;
pub const SNDRV_TIMER_EVENT_EARLY: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_EARLY;
pub const SNDRV_TIMER_EVENT_SUSPEND: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_SUSPEND;
pub const SNDRV_TIMER_EVENT_RESUME: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_RESUME;
pub const SNDRV_TIMER_EVENT_MSTART: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_MSTART;
pub const SNDRV_TIMER_EVENT_MSTOP: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_MSTOP;
pub const SNDRV_TIMER_EVENT_MCONTINUE: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_MCONTINUE;
pub const SNDRV_TIMER_EVENT_MPAUSE: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_MPAUSE;
pub const SNDRV_TIMER_EVENT_MSUSPEND: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_MSUSPEND;
pub const SNDRV_TIMER_EVENT_MRESUME: _bindgen_ty_13 = _bindgen_ty_13::SNDRV_TIMER_EVENT_MRESUME;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_1 {
SNDRV_HWDEP_IFACE_OPL2 = 0,
SNDRV_HWDEP_IFACE_OPL3 = 1,
SNDRV_HWDEP_IFACE_OPL4 = 2,
SNDRV_HWDEP_IFACE_SB16CSP = 3,
SNDRV_HWDEP_IFACE_EMU10K1 = 4,
SNDRV_HWDEP_IFACE_YSS225 = 5,
SNDRV_HWDEP_IFACE_ICS2115 = 6,
SNDRV_HWDEP_IFACE_SSCAPE = 7,
SNDRV_HWDEP_IFACE_VX = 8,
SNDRV_HWDEP_IFACE_MIXART = 9,
SNDRV_HWDEP_IFACE_USX2Y = 10,
SNDRV_HWDEP_IFACE_EMUX_WAVETABLE = 11,
SNDRV_HWDEP_IFACE_BLUETOOTH = 12,
SNDRV_HWDEP_IFACE_USX2Y_PCM = 13,
SNDRV_HWDEP_IFACE_PCXHR = 14,
SNDRV_HWDEP_IFACE_SB_RC = 15,
SNDRV_HWDEP_IFACE_HDA = 16,
SNDRV_HWDEP_IFACE_USB_STREAM = 17,
SNDRV_HWDEP_IFACE_FW_DICE = 18,
SNDRV_HWDEP_IFACE_FW_FIREWORKS = 19,
SNDRV_HWDEP_IFACE_FW_BEBOB = 20,
SNDRV_HWDEP_IFACE_FW_OXFW = 21,
SNDRV_HWDEP_IFACE_FW_DIGI00X = 22,
SNDRV_HWDEP_IFACE_FW_TASCAM = 23,
SNDRV_HWDEP_IFACE_LINE6 = 24,
SNDRV_HWDEP_IFACE_FW_MOTU = 25,
SNDRV_HWDEP_IFACE_FW_FIREFACE = 26,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_2 {
SNDRV_PCM_CLASS_GENERIC = 0,
SNDRV_PCM_CLASS_MULTI = 1,
SNDRV_PCM_CLASS_MODEM = 2,
SNDRV_PCM_CLASS_DIGITIZER = 3,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_3 {
SNDRV_PCM_SUBCLASS_GENERIC_MIX = 0,
SNDRV_PCM_SUBCLASS_MULTI_MIX = 1,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_4 {
SNDRV_PCM_STREAM_PLAYBACK = 0,
SNDRV_PCM_STREAM_CAPTURE = 1,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_5 {
SNDRV_PCM_MMAP_OFFSET_DATA = 0,
SNDRV_PCM_MMAP_OFFSET_STATUS_OLD = 2147483648,
SNDRV_PCM_MMAP_OFFSET_CONTROL_OLD = 2164260864,
SNDRV_PCM_MMAP_OFFSET_STATUS_NEW = 2181038080,
SNDRV_PCM_MMAP_OFFSET_CONTROL_NEW = 2197815296,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_6 {
SNDRV_PCM_TSTAMP_NONE = 0,
SNDRV_PCM_TSTAMP_ENABLE = 1,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_7 {
SNDRV_PCM_AUDIO_TSTAMP_TYPE_COMPAT = 0,
SNDRV_PCM_AUDIO_TSTAMP_TYPE_DEFAULT = 1,
SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK = 2,
SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_ABSOLUTE = 3,
SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_ESTIMATED = 4,
SNDRV_PCM_AUDIO_TSTAMP_TYPE_LINK_SYNCHRONIZED = 5,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_8 {
SNDRV_PCM_TSTAMP_TYPE_GETTIMEOFDAY = 0,
SNDRV_PCM_TSTAMP_TYPE_MONOTONIC = 1,
SNDRV_PCM_TSTAMP_TYPE_MONOTONIC_RAW = 2,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_9 {
SNDRV_CHMAP_UNKNOWN = 0,
SNDRV_CHMAP_NA = 1,
SNDRV_CHMAP_MONO = 2,
SNDRV_CHMAP_FL = 3,
SNDRV_CHMAP_FR = 4,
SNDRV_CHMAP_RL = 5,
SNDRV_CHMAP_RR = 6,
SNDRV_CHMAP_FC = 7,
SNDRV_CHMAP_LFE = 8,
SNDRV_CHMAP_SL = 9,
SNDRV_CHMAP_SR = 10,
SNDRV_CHMAP_RC = 11,
SNDRV_CHMAP_FLC = 12,
SNDRV_CHMAP_FRC = 13,
SNDRV_CHMAP_RLC = 14,
SNDRV_CHMAP_RRC = 15,
SNDRV_CHMAP_FLW = 16,
SNDRV_CHMAP_FRW = 17,
SNDRV_CHMAP_FLH = 18,
SNDRV_CHMAP_FCH = 19,
SNDRV_CHMAP_FRH = 20,
SNDRV_CHMAP_TC = 21,
SNDRV_CHMAP_TFL = 22,
SNDRV_CHMAP_TFR = 23,
SNDRV_CHMAP_TFC = 24,
SNDRV_CHMAP_TRL = 25,
SNDRV_CHMAP_TRR = 26,
SNDRV_CHMAP_TRC = 27,
SNDRV_CHMAP_TFLC = 28,
SNDRV_CHMAP_TFRC = 29,
SNDRV_CHMAP_TSL = 30,
SNDRV_CHMAP_TSR = 31,
SNDRV_CHMAP_LLFE = 32,
SNDRV_CHMAP_RLFE = 33,
SNDRV_CHMAP_BC = 34,
SNDRV_CHMAP_BLC = 35,
SNDRV_CHMAP_BRC = 36,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_10 {
SNDRV_RAWMIDI_STREAM_OUTPUT = 0,
SNDRV_RAWMIDI_STREAM_INPUT = 1,
}
#[repr(i32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_11 {
SNDRV_TIMER_CLASS_NONE = -1,
SNDRV_TIMER_CLASS_SLAVE = 0,
SNDRV_TIMER_CLASS_GLOBAL = 1,
SNDRV_TIMER_CLASS_CARD = 2,
SNDRV_TIMER_CLASS_PCM = 3,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_12 {
SNDRV_TIMER_SCLASS_NONE = 0,
SNDRV_TIMER_SCLASS_APPLICATION = 1,
SNDRV_TIMER_SCLASS_SEQUENCER = 2,
SNDRV_TIMER_SCLASS_OSS_SEQUENCER = 3,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_13 {
SNDRV_TIMER_EVENT_RESOLUTION = 0,
SNDRV_TIMER_EVENT_TICK = 1,
SNDRV_TIMER_EVENT_START = 2,
SNDRV_TIMER_EVENT_STOP = 3,
SNDRV_TIMER_EVENT_CONTINUE = 4,
SNDRV_TIMER_EVENT_PAUSE = 5,
SNDRV_TIMER_EVENT_EARLY = 6,
SNDRV_TIMER_EVENT_SUSPEND = 7,
SNDRV_TIMER_EVENT_RESUME = 8,
SNDRV_TIMER_EVENT_MSTART = 12,
SNDRV_TIMER_EVENT_MSTOP = 13,
SNDRV_TIMER_EVENT_MCONTINUE = 14,
SNDRV_TIMER_EVENT_MPAUSE = 15,
SNDRV_TIMER_EVENT_MSUSPEND = 17,
SNDRV_TIMER_EVENT_MRESUME = 18,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum sndrv_ctl_event_type {
SNDRV_CTL_EVENT_ELEM = 0,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_pcm_sync_id {
pub id: [crate::ctypes::c_uchar; 16usize],
pub id16: [crate::ctypes::c_ushort; 8usize],
pub id32: [crate::ctypes::c_uint; 4usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_pcm_sync_ptr__bindgen_ty_1 {
pub status: snd_pcm_mmap_status,
pub reserved: [crate::ctypes::c_uchar; 64usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_pcm_sync_ptr__bindgen_ty_2 {
pub control: snd_pcm_mmap_control,
pub reserved: [crate::ctypes::c_uchar; 64usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_ctl_elem_info__bindgen_ty_1 {
pub integer: snd_ctl_elem_info__bindgen_ty_1__bindgen_ty_1,
pub integer64: snd_ctl_elem_info__bindgen_ty_1__bindgen_ty_2,
pub enumerated: snd_ctl_elem_info__bindgen_ty_1__bindgen_ty_3,
pub reserved: [crate::ctypes::c_uchar; 128usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_ctl_elem_value__bindgen_ty_1 {
pub integer: snd_ctl_elem_value__bindgen_ty_1__bindgen_ty_1,
pub integer64: snd_ctl_elem_value__bindgen_ty_1__bindgen_ty_2,
pub enumerated: snd_ctl_elem_value__bindgen_ty_1__bindgen_ty_3,
pub bytes: snd_ctl_elem_value__bindgen_ty_1__bindgen_ty_4,
pub iec958: snd_aes_iec958,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_ctl_elem_value__bindgen_ty_1__bindgen_ty_1 {
pub value: [crate::ctypes::c_long; 128usize],
pub value_ptr: *mut crate::ctypes::c_long,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_ctl_elem_value__bindgen_ty_1__bindgen_ty_2 {
pub value: [crate::ctypes::c_longlong; 64usize],
pub value_ptr: *mut crate::ctypes::c_longlong,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_ctl_elem_value__bindgen_ty_1__bindgen_ty_3 {
pub item: [crate::ctypes::c_uint; 128usize],
pub item_ptr: *mut crate::ctypes::c_uint,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_ctl_elem_value__bindgen_ty_1__bindgen_ty_4 {
pub data: [crate::ctypes::c_uchar; 512usize],
pub data_ptr: *mut crate::ctypes::c_uchar,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union snd_ctl_event__bindgen_ty_1 {
pub elem: snd_ctl_event__bindgen_ty_1__bindgen_ty_1,
pub data8: [crate::ctypes::c_uchar; 60usize],
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
#[inline]
pub const fn new(storage: Storage) -> Self {
Self { storage }
}
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
Storage: AsRef<[u8]> + AsMut<[u8]>,
{
#[inline]
fn extract_bit(byte: u8, index: usize) -> bool {
let bit_index = if cfg!(target_endian = "big") { 7 - (index % 8) } else { index % 8 };
let mask = 1 << bit_index;
byte & mask == mask
}
#[inline]
pub fn get_bit(&self, index: usize) -> bool {
debug_assert!(index / 8 < self.storage.as_ref().len());
let byte_index = index / 8;
let byte = self.storage.as_ref()[byte_index];
Self::extract_bit(byte, index)
}
#[inline]
pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
debug_assert!(index / 8 < core::mem::size_of::<Storage>());
let byte_index = index / 8;
let byte = unsafe { *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize) };
Self::extract_bit(byte, index)
}
#[inline]
fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
let bit_index = if cfg!(target_endian = "big") { 7 - (index % 8) } else { index % 8 };
let mask = 1 << bit_index;
if val {
byte | mask
} else {
byte & !mask
}
}
#[inline]
pub fn set_bit(&mut self, index: usize, val: bool) {
debug_assert!(index / 8 < self.storage.as_ref().len());
let byte_index = index / 8;
let byte = &mut self.storage.as_mut()[byte_index];
*byte = Self::change_bit(*byte, index, val);
}
#[inline]
pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
debug_assert!(index / 8 < core::mem::size_of::<Storage>());
let byte_index = index / 8;
let byte = unsafe { (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize) };
unsafe { *byte = Self::change_bit(*byte, index, val) };
}
#[inline]
pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
debug_assert!(bit_width <= 64);
debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
let mut val = 0;
for i in 0..(bit_width as usize) {
if self.get_bit(i + bit_offset) {
let index = if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
val |= 1 << index;
}
}
val
}
#[inline]
pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
debug_assert!(bit_width <= 64);
debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
let mut val = 0;
for i in 0..(bit_width as usize) {
if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
let index = if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
val |= 1 << index;
}
}
val
}
#[inline]
pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
debug_assert!(bit_width <= 64);
debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
for i in 0..(bit_width as usize) {
let mask = 1 << i;
let val_bit_is_set = val & mask == mask;
let index = if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
self.set_bit(index + bit_offset, val_bit_is_set);
}
}
#[inline]
pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
debug_assert!(bit_width <= 64);
debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
for i in 0..(bit_width as usize) {
let mask = 1 << i;
let val_bit_is_set = val & mask == mask;
let index = if cfg!(target_endian = "big") { bit_width as usize - 1 - i } else { i };
unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
}
}
}
impl<T> __IncompleteArrayField<T> {
#[inline]
pub const fn new() -> Self {
__IncompleteArrayField(::core::marker::PhantomData, [])
}
#[inline]
pub fn as_ptr(&self) -> *const T {
self as *const _ as *const T
}
#[inline]
pub fn as_mut_ptr(&mut self) -> *mut T {
self as *mut _ as *mut T
}
#[inline]
pub unsafe fn as_slice(&self, len: usize) -> &[T] {
::core::slice::from_raw_parts(self.as_ptr(), len)
}
#[inline]
pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
}
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
fmt.write_str("__IncompleteArrayField")
}
}
impl<T> __BindgenUnionField<T> {
#[inline]
pub const fn new() -> Self {
__BindgenUnionField(::core::marker::PhantomData)
}
#[inline]
pub unsafe fn as_ref(&self) -> &T {
::core::mem::transmute(self)
}
#[inline]
pub unsafe fn as_mut(&mut self) -> &mut T {
::core::mem::transmute(self)
}
}
impl<T> ::core::default::Default for __BindgenUnionField<T> {
#[inline]
fn default() -> Self {
Self::new()
}
}
impl<T> ::core::clone::Clone for __BindgenUnionField<T> {
#[inline]
fn clone(&self) -> Self {
*self
}
}
impl<T> ::core::marker::Copy for __BindgenUnionField<T> {}
impl<T> ::core::fmt::Debug for __BindgenUnionField<T> {
fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
fmt.write_str("__BindgenUnionField")
}
}
impl<T> ::core::hash::Hash for __BindgenUnionField<T> {
fn hash<H: ::core::hash::Hasher>(&self, _state: &mut H) {}
}
impl<T> ::core::cmp::PartialEq for __BindgenUnionField<T> {
fn eq(&self, _other: &__BindgenUnionField<T>) -> bool {
true
}
}
impl<T> ::core::cmp::Eq for __BindgenUnionField<T> {}
impl snd_interval {
#[inline]
pub fn openmin(&self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
}
#[inline]
pub fn set_openmin(&mut self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
self._bitfield_1.set(0usize, 1u8, val as u64)
}
}
#[inline]
pub unsafe fn openmin_raw(this: *const Self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(::core::ptr::addr_of!((*this)._bitfield_1), 0usize, 1u8) as u32) }
}
#[inline]
pub unsafe fn set_openmin_raw(this: *mut Self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(::core::ptr::addr_of_mut!((*this)._bitfield_1), 0usize, 1u8, val as u64)
}
}
#[inline]
pub fn openmax(&self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(self._bitfield_1.get(1usize, 1u8) as u32) }
}
#[inline]
pub fn set_openmax(&mut self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
self._bitfield_1.set(1usize, 1u8, val as u64)
}
}
#[inline]
pub unsafe fn openmax_raw(this: *const Self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(::core::ptr::addr_of!((*this)._bitfield_1), 1usize, 1u8) as u32) }
}
#[inline]
pub unsafe fn set_openmax_raw(this: *mut Self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(::core::ptr::addr_of_mut!((*this)._bitfield_1), 1usize, 1u8, val as u64)
}
}
#[inline]
pub fn integer(&self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(self._bitfield_1.get(2usize, 1u8) as u32) }
}
#[inline]
pub fn set_integer(&mut self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
self._bitfield_1.set(2usize, 1u8, val as u64)
}
}
#[inline]
pub unsafe fn integer_raw(this: *const Self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(::core::ptr::addr_of!((*this)._bitfield_1), 2usize, 1u8) as u32) }
}
#[inline]
pub unsafe fn set_integer_raw(this: *mut Self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(::core::ptr::addr_of_mut!((*this)._bitfield_1), 2usize, 1u8, val as u64)
}
}
#[inline]
pub fn empty(&self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(self._bitfield_1.get(3usize, 1u8) as u32) }
}
#[inline]
pub fn set_empty(&mut self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
self._bitfield_1.set(3usize, 1u8, val as u64)
}
}
#[inline]
pub unsafe fn empty_raw(this: *const Self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(::core::ptr::addr_of!((*this)._bitfield_1), 3usize, 1u8) as u32) }
}
#[inline]
pub unsafe fn set_empty_raw(this: *mut Self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(::core::ptr::addr_of_mut!((*this)._bitfield_1), 3usize, 1u8, val as u64)
}
}
#[inline]
pub fn new_bitfield_1(openmin: crate::ctypes::c_uint, openmax: crate::ctypes::c_uint, integer: crate::ctypes::c_uint, empty: crate::ctypes::c_uint) -> __BindgenBitfieldUnit<[u8; 1usize]> {
let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
__bindgen_bitfield_unit.set(0usize, 1u8, {
let openmin: u32 = unsafe { ::core::mem::transmute(openmin) };
openmin as u64
});
__bindgen_bitfield_unit.set(1usize, 1u8, {
let openmax: u32 = unsafe { ::core::mem::transmute(openmax) };
openmax as u64
});
__bindgen_bitfield_unit.set(2usize, 1u8, {
let integer: u32 = unsafe { ::core::mem::transmute(integer) };
integer as u64
});
__bindgen_bitfield_unit.set(3usize, 1u8, {
let empty: u32 = unsafe { ::core::mem::transmute(empty) };
empty as u64
});
__bindgen_bitfield_unit
}
}
impl snd_rawmidi_params {
#[inline]
pub fn no_active_sensing(&self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
}
#[inline]
pub fn set_no_active_sensing(&mut self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
self._bitfield_1.set(0usize, 1u8, val as u64)
}
}
#[inline]
pub unsafe fn no_active_sensing_raw(this: *const Self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(::core::ptr::addr_of!((*this)._bitfield_1), 0usize, 1u8) as u32) }
}
#[inline]
pub unsafe fn set_no_active_sensing_raw(this: *mut Self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(::core::ptr::addr_of_mut!((*this)._bitfield_1), 0usize, 1u8, val as u64)
}
}
#[inline]
pub fn new_bitfield_1(no_active_sensing: crate::ctypes::c_uint) -> __BindgenBitfieldUnit<[u8; 1usize]> {
let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
__bindgen_bitfield_unit.set(0usize, 1u8, {
let no_active_sensing: u32 = unsafe { ::core::mem::transmute(no_active_sensing) };
no_active_sensing as u64
});
__bindgen_bitfield_unit
}
}
impl snd_ctl_elem_value {
#[inline]
pub fn indirect(&self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
}
#[inline]
pub fn set_indirect(&mut self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
self._bitfield_1.set(0usize, 1u8, val as u64)
}
}
#[inline]
pub unsafe fn indirect_raw(this: *const Self) -> crate::ctypes::c_uint {
unsafe { ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(::core::ptr::addr_of!((*this)._bitfield_1), 0usize, 1u8) as u32) }
}
#[inline]
pub unsafe fn set_indirect_raw(this: *mut Self, val: crate::ctypes::c_uint) {
unsafe {
let val: u32 = ::core::mem::transmute(val);
<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(::core::ptr::addr_of_mut!((*this)._bitfield_1), 0usize, 1u8, val as u64)
}
}
#[inline]
pub fn new_bitfield_1(indirect: crate::ctypes::c_uint) -> __BindgenBitfieldUnit<[u8; 1usize]> {
let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
__bindgen_bitfield_unit.set(0usize, 1u8, {
let indirect: u32 = unsafe { ::core::mem::transmute(indirect) };
indirect as u64
});
__bindgen_bitfield_unit
}
}
impl sndrv_ctl_event_type {
pub const SNDRV_CTL_EVENT_LAST: sndrv_ctl_event_type = sndrv_ctl_event_type::SNDRV_CTL_EVENT_ELEM;
}
